version: '3.8'
services:
  rust_bot:
    build:
      context: .
      dockerfile: docker/dev.dockerfile # Specify the correct Dockerfile name
    ports:
      - "3000:3000" # Map the host port to the container port
    volumes:
      - ./rust_bot/static:/usr/local/bin/static # Assuming you have a local directory named rust_bot/static
      - ./rust_bot/data:/usr/local/bin/data # Assuming you have a local directory named rust_bot/data
    environment:
      - RUST_LOG=info # Set environment variables if needed
    restart: unless-stopped # Restart policy for the container

