version: '3.8'
services:
  rust_bot:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./rust_bot/static:/usr/local/bin/static
      - ./rust_bot/.env:/usr/local/bin/.env # Mount the .env file
    environment:
      - RUST_LOG=info
    restart: unless-stopped

