image:
  repository: 930985312118.dkr.ecr.eu-central-1.amazonaws.com/chat-bot
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: dev-86

podAnnotations:
  linkerd.io/inject: enabled

resources:
  limits:
    memory: "4Gi"
  requests:
    memory: "1Gi"

startupProbe:
  httpGet:
    path: /health
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 40
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 30

livenessProbe:
  httpGet:
    path: /health
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 30
  failureThreshold: 8
  periodSeconds: 1
  successThreshold: 1
  timeoutSeconds: 4

readinessProbe:
  httpGet:
    path: /health
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 30
  failureThreshold: 5
  periodSeconds: 1
  successThreshold: 1
  timeoutSeconds: 4

containerPort: 3000
service:
  enabled: true
  name: http
  type: NodePort
  port: 80
  protocol: TCP
  annotations:
    linkerd.io/inject: enabled

replicaCount: 2
labels:
  label1:
    name: "app-version"
    value: "v0.0.1"
