image:
  repository: 930985312118.dkr.ecr.eu-central-1.amazonaws.com/chat-bot
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: dev-86

podAnnotations:
  linkerd.io/inject: enabled

resources:
  limits:
    memory: "4Gi"
  requests:
    memory: "1Gi"

containerPort: 3000
service:
  enabled: true
  name: http
  type: NodePort
  port: 80
  protocol: TCP
  annotations:
    linkerd.io/inject: enabled

replicaCount: 2
labels:
  label1:
    name: "app-version"
    value: "v0.0.1"
