image:
  repository: 930985312118.dkr.ecr.eu-central-1.amazonaws.com/chat-bot
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: dev-86

podAnnotations:
  linkerd.io/inject: enabled

resources:
  limits:
    memory: "4Gi"
  requests:
    memory: "1Gi"

readinessProbe:
  exec:
    command:
      - sh
      - -c
      - >
        curl -o /dev/null -s -w "%{http_code}" -X POST https://assistant.buycycle.com/assistant -H "Content-Type: application/x-www-form-urlencoded" -d 'user_id=test_user&message=test.' | grep 200

  initialDelaySeconds: 10
  periodSeconds: 60
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
livenessProbe:
  exec:
    command:
      - sh
      - -c
      - >
        curl -o /dev/null -s -w "%{http_code}" -X POST https://assistant.buycycle.com/assistant -H "Content-Type: application/x-www-form-urlencoded" -d 'user_id=test_user&message=test.' | grep 200

  initialDelaySeconds: 30
  periodSeconds: 120
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

containerPort: 3000
service:
  enabled: true
  name: http
  type: NodePort
  port: 80
  protocol: TCP
  annotations:
    linkerd.io/inject: enabled

replicaCount: 2
labels:
  label1:
    name: "app-version"
    value: "v0.0.1"
